name: Continuous Integration

on:
  push:

  pull_request:

env:
  PUBLISH_IMAGE: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'TRUE' || 'FALSE'}}
  IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}/arpav-ppcv

jobs:
  run-dagger-ci:
    runs-on: ubuntu-22.04
    steps:

      - name: grab code
        uses: actions/checkout@v4

      - name: login to container registry
        if: ${{ env.PUBLISH_IMAGE == 'TRUE' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_FOR_REGISTRY }}
          password: ${{ secrets.PAT_FOR_REGISTRY }}

      - name: run ci
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.14.0"
          verb: call
          module: continuous-integration
          args: >-
            build-image
            --repo-root-path=.
            ${{ env.PUBLISH_IMAGE == 'TRUE' && format('--publish-docker-image {0}:{1}', env.IMAGE_NAME, env.IMAGE_TAG)  || ''}}
